// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingCompanyApp;

#nullable disable

namespace TradingCompanyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311012126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingCompanyApp.Models.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.ReleaseRequest", b =>
                {
                    b.Property<int>("ReleaseRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReleaseRequestId"));

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ReleaseRequestId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseName");

                    b.ToTable("ReleaseRequest");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.ReleaseRequestItem", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("RequestId", "ItemCode");

                    b.HasIndex("WarehouseId", "ItemCode");

                    b.ToTable("Release_Request_Items");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.SupplyRequest", b =>
                {
                    b.Property<int>("SupplyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyRequestId"));

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("SupplyRequestId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseName");

                    b.ToTable("SupplyRequest");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.SupplyRequestItem", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("RequestId", "ItemCode");

                    b.HasIndex("WarehouseId", "ItemCode");

                    b.ToTable("SupplyRequestItem");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Username")
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("WarehouseId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.WarehouseItem", b =>
                {
                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("WarehouseId", "ItemCode");

                    b.HasIndex("ItemCode");

                    b.ToTable("WarehouseItem");
                });

            modelBuilder.Entity("WarehouseUsers", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseUsers");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Customer", b =>
                {
                    b.HasBaseType("TradingCompanyApp.Models.User");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Employee", b =>
                {
                    b.HasBaseType("TradingCompanyApp.Models.User");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Supplier", b =>
                {
                    b.HasBaseType("TradingCompanyApp.Models.User");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("TradingCompanyApp.Models.ReleaseRequest", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingCompanyApp.Models.Warehouse", "Warehouse")
                        .WithMany("ReleaseRequests")
                        .HasForeignKey("WarehouseName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.ReleaseRequestItem", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.ReleaseRequest", "ReleaseRequest")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingCompanyApp.Models.WarehouseItem", "Item")
                        .WithMany()
                        .HasForeignKey("WarehouseId", "ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ReleaseRequest");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.SupplyRequest", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingCompanyApp.Models.Warehouse", "Warehouse")
                        .WithMany("SupplyRequests")
                        .HasForeignKey("WarehouseName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.SupplyRequestItem", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.SupplyRequest", "SupplyRequest")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingCompanyApp.Models.WarehouseItem", "Item")
                        .WithMany()
                        .HasForeignKey("WarehouseId", "ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SupplyRequest");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Warehouse", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.WarehouseItem", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingCompanyApp.Models.Warehouse", "Warehouse")
                        .WithMany("Items")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseUsers", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingCompanyApp.Models.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Customer", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TradingCompanyApp.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Employee", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TradingCompanyApp.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Supplier", b =>
                {
                    b.HasOne("TradingCompanyApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TradingCompanyApp.Models.Supplier", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingCompanyApp.Models.ReleaseRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.SupplyRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TradingCompanyApp.Models.Warehouse", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ReleaseRequests");

                    b.Navigation("SupplyRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
